### PR TITLE
Added selectDB and createDB, and included them in readme

### PR DESCRIPTION
**Pull request by shershams**
This fixes #15.

### CODE REVIEW

**Comment by julien-c** [comment]
I'm curious, in which cases do you actually need those? (seeing as Mongo lazily creates databases and collections)

**Comment by shershams** [comment]
I was just thinking the case where you want to switch between databases - this is happening in our project, each client has their own database and there's also global database. And the purpose of `createDB` is to switch to the new db to start adding data into it. Actually, we could just keep the `selectDB` and we don't really need `createDB`.

**Comment by navruzm** [comment]
Currently selectDB return a MongoDB instance. If you want to get MongoDB, just do 

``` php
$lmongo->getMongoClient()->selectDB('yourdatabase');
```

If you use Eloquent, `selectDB` can cause problems. For example:

``` php
User::all(); 
//No problem. We get all the users from default database.

LMongo::selectDB('test')->doWhatever();
//We change database and do some work

User::all();
//Problem! User model connected to test database. 
//Because we set \LMongo\Connection->db to test
```

**Comment by shershams** [comment]
Yeah this makes sense. Closing the ticket.

**Comment by shershams** [comment]
Is there a way to set the DB in LMongo then? `$lmongo->getMongoClient()->selectDB('yourdatabase');` returns mongo db instance, but how can I use it to use builder in lmongo?

**Comment by navruzm** [comment]
Currently you can't use QB with `$lmongo->getMongoClient()->selectDB('yourdatabase');` It returns MongoDB instance not QB as explained above. 

Maybe we can implement this feature in future but now i'm closing this.

**Pull request closed without merging**
